project:
  type: website

website:
  title: "Critical AI Literacy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: topics/index.qmd
        text: Topics
      - href: use_cases/index.qmd
        text: Use Cases
      - href: references_resources.qmd
        text: References and further Resources
      - href: alternatives.qmd
        text: Alternatives

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true



