project:
  type: website

website:
  title: "Critical AI Literacy: Reflective use (or non-use) of GenerativeAI systems"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: topics/index.qmd
        text: Topics

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true



