---
title: "Use cases"
#listing:
#  type: grid
page-layout: full

comments: false
format:
  html:
    theme: 
        - cosmo
        - ../styles.scss
---


# General questions

- Is your cognitive labour being affected by using a GenAI chatbot (or any AI tool)? [adapted from @guestsuarezrooij2025]
- Do you learn what you are supposed to learn?
- Can the use of AI be justified given the ethical and environmental concerns of AI tools?
- What exactly do you expect to gain by using GenAI chatbot (or any AI tool)? Could the task me carried out using other means? 


# Development of ideas

## Discussion questions

- How may the engagement with AI both positively and negatively influence the development of ideas?
  - Think about the goals of the design of the tool vs. your own particular goals ([add pointer to Interaction]{style="color:red"})
  - Think about bias in the model output ([add pointer to Data]{style="color:red"})
- What is the difference between regarding research as a process rather than as a product? Why should “serendipity” matter to this process? ([add reference LD]{style="color:red"})

## Teaching ideas

# Literature review

## Discussion questions

- What are the limitations of these sytems given their training data? Is the information needed actually in the training data?
- What is the point of citation, practically as well as ethically? 
- How does a collaboratively built resource such as Wikipedia, or a peer-reviewed academic resource, differ from generative AI tools such as ChatGPT or Perplexity AI? (from LD)


## Teaching ideas

# Writing

## Discussion questions

- Do we by citing a chatbot or acknowledging the use of a chatbot avoid plagiarising?
- Are there other potential tools that may be more suitable for the task?

## Teaching ideas

- Ask students to write a short essay (approx. 300 words) on a particular topic. The students are then asked to compare two texts, one written by a classmate and one written by a GenAI chatbot without knowing who wrote which one. Subsequently the students can discuss how the two texts differ in style and content and whether they could tell who wrote which text. 


# Coding

- for the use of AI in coding and learning how to code, see [Chapter 15](https://elenlefoll.github.io/RstatsTextbook/15_AI.html) in @lefoll


# Linguistics-specific

## Discussion questions


## Teaching ideas



# References